version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: loadpulse-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  loadpulse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loadpulse-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB: loadpulse
      CLIENT_ORIGIN: http://localhost:4000
    ports:
      - "4000:4000"
    depends_on:
      - mongo

volumes:
  mongo-data:
